// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgrammingCoursesManger.Database;

#nullable disable

namespace ProgrammingCoursesManger.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220404103924_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProgrammingCoursesManger.Database.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Podstawy języka C#",
                            Name = "Kurs C# I"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Skomplikowane strukury języka C# oraz praktyczne przykłady zastosowania",
                            Name = "Kurs C# II"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Podstawy języka węży",
                            Name = "Kurs Python I"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Jak otworzyć chodowlę węży",
                            Name = "Kurs Python II"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nauka projektowania stron internetowych od podstaw",
                            Name = "Kurs HTML/JS"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Omówienie projektowania stron internetowych zarówno statycznych jak i SPA na przykładach w najpopularniejszych frameworkach JavaScript/TypeScript",
                            Name = "Kurs HTML/JS/TS"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Wprowadzenie do frameworka Angular zarówno dla początkujących jak i zaawansowanych",
                            Name = "Kurs Angular"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Wprowadzenie do frameworka React zarówno dla początkujących jak i zaawansowanych",
                            Name = "Kurs React"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Wprowadzenie do frameworka Vue zarówno dla początkujących jak i zaawansowanych",
                            Name = "Kurs Vue"
                        });
                });

            modelBuilder.Entity("ProgrammingCoursesManger.Database.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Name = "C# I - Temat 1",
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Name = "C# I - Temat 2",
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            Name = "C# I - Temat 3",
                            Number = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            Name = "C# II - Temat 1",
                            Number = 1
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            Name = "C# II - Temat 2",
                            Number = 2
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            Name = "C# II - Temat 3",
                            Number = 3
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 3,
                            Name = "Python I - Temat 1",
                            Number = 1
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 3,
                            Name = "Python I - Temat 2",
                            Number = 2
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 3,
                            Name = "Python I - Temat 3",
                            Number = 3
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 3,
                            Name = "Python I - Temat 4",
                            Number = 4
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 3,
                            Name = "Python I - Temat 5",
                            Number = 5
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 4,
                            Name = "Python II - Temat 1",
                            Number = 1
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 4,
                            Name = "Python II - Temat 2",
                            Number = 2
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 5,
                            Name = "HTML",
                            Number = 1
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 5,
                            Name = "JavaScript",
                            Number = 2
                        },
                        new
                        {
                            Id = 16,
                            CourseId = 6,
                            Name = "HTML",
                            Number = 1
                        },
                        new
                        {
                            Id = 17,
                            CourseId = 6,
                            Name = "JavaScript - Temat 1",
                            Number = 2
                        },
                        new
                        {
                            Id = 18,
                            CourseId = 6,
                            Name = "JavaScript - Temat 2",
                            Number = 3
                        },
                        new
                        {
                            Id = 19,
                            CourseId = 6,
                            Name = "JavaScript - Temat 3",
                            Number = 4
                        },
                        new
                        {
                            Id = 20,
                            CourseId = 6,
                            Name = "JavaScript - Temat 4",
                            Number = 5
                        },
                        new
                        {
                            Id = 21,
                            CourseId = 6,
                            Name = "TypeScript - Temat 1",
                            Number = 6
                        },
                        new
                        {
                            Id = 22,
                            CourseId = 6,
                            Name = "TypeScript - Temat 2",
                            Number = 7
                        },
                        new
                        {
                            Id = 23,
                            CourseId = 6,
                            Name = "Angular",
                            Number = 8
                        },
                        new
                        {
                            Id = 24,
                            CourseId = 6,
                            Name = "React",
                            Number = 9
                        },
                        new
                        {
                            Id = 25,
                            CourseId = 6,
                            Name = "Vue",
                            Number = 10
                        },
                        new
                        {
                            Id = 26,
                            CourseId = 7,
                            Name = "JavaScript",
                            Number = 1
                        },
                        new
                        {
                            Id = 27,
                            CourseId = 7,
                            Name = "Angular - Temat 1",
                            Number = 2
                        },
                        new
                        {
                            Id = 28,
                            CourseId = 7,
                            Name = "Angular - Temat 2",
                            Number = 3
                        },
                        new
                        {
                            Id = 29,
                            CourseId = 7,
                            Name = "Angular - Temat 3",
                            Number = 4
                        },
                        new
                        {
                            Id = 30,
                            CourseId = 7,
                            Name = "Angular - Temat 4",
                            Number = 5
                        },
                        new
                        {
                            Id = 31,
                            CourseId = 8,
                            Name = "JavaScript",
                            Number = 1
                        },
                        new
                        {
                            Id = 32,
                            CourseId = 8,
                            Name = "React - Temat 1",
                            Number = 2
                        },
                        new
                        {
                            Id = 33,
                            CourseId = 8,
                            Name = "React - Temat 2",
                            Number = 3
                        },
                        new
                        {
                            Id = 34,
                            CourseId = 8,
                            Name = "React - Temat 3",
                            Number = 4
                        },
                        new
                        {
                            Id = 35,
                            CourseId = 9,
                            Name = "JavaScript",
                            Number = 1
                        },
                        new
                        {
                            Id = 36,
                            CourseId = 9,
                            Name = "Vue - Temat 1",
                            Number = 2
                        },
                        new
                        {
                            Id = 37,
                            CourseId = 9,
                            Name = "Vue - Temat 2",
                            Number = 3
                        });
                });

            modelBuilder.Entity("ProgrammingCoursesManger.Database.Models.Topic", b =>
                {
                    b.HasOne("ProgrammingCoursesManger.Database.Models.Course", "Course")
                        .WithMany("Topics")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ProgrammingCoursesManger.Database.Models.Course", b =>
                {
                    b.Navigation("Topics");
                });
#pragma warning restore 612, 618
        }
    }
}
